version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project  
  variables:
    CACHE_CONTROL: "86400"
    BUILD_ENV: "prod"
    S3_BUCKET : "cicdangular"
    BUILD_FOLDER : "dist"  
phases:
    install:
        runtime-versions:
            nodejs: 10
    pre_build:        
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
            - apt-get update
            - apt-get install -y jq
            - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
            - tar xzf apache-maven-3.5.4-bin.tar.gz
            - ln -s apache-maven-3.5.4 maven
            - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
            - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
            - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
    build:
        commands:
            - echo Build started on `date`
            - ng build 
            - mvn test     
            - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
            - sleep 5
            - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
            - cat result.json
            - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
    post_build:
     commands:
      - echo Build completed on `date`
       -aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive

artifacts:    
  files:
    - '**/*'
  base-directory: 'dist*'

artifacts: 
  base-directory: dist*
  files: 
    - "*/*"
    - 'appspec.yml'
    - 'scripts'
    - 'app.js'

