version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_ENV: "prod"
        S3_BUCKET : "cicdangular"
        BUILD_FOLDER : "dist"
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build 
    post_build:
     commands:
      - echo Build completed on `date`
       -aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive

artifacts:    
  files:
    - '**/*'
  base-directory: 'dist*'

artifacts: 
  base-directory: dist*
  files: 
    - "*/*"
    - 'appspec.yml'
    - 'scripts'
    - 'app.js'

